"""add general settings to app

Revision ID: 8fe407cf56c9
Revises: 3c466ce2ab63
Create Date: 2025-07-08 15:48:02.163498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fe407cf56c9'
down_revision = '3c466ce2ab63'
branch_labels = None
depends_on = None

def upgrade() -> None:
    op.add_column('settings', sa.Column('general', sa.JSON(), nullable=False, server_default="{\"default_flow\": \"\",\"default_method\": \"chacha20-ietf-poly1305\"}"))

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'general')
    # ### end Alembic commands ###
