"""add priority to proxy hosts

Revision ID: c5c734bd3da2
Revises: 68edca039166
Create Date: 2025-02-24 22:29:49.063544

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision = "c5c734bd3da2"
down_revision = "68edca039166"
branch_labels = None
depends_on = None


is_sqlite = op.get_bind().dialect.name == "sqlite"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column("hosts", sa.Column("priority", sa.Integer(), nullable=True))
    op.execute("UPDATE hosts SET priority = id")

    with op.batch_alter_table("hosts") as batch_op:
        # Handle priority column first
        batch_op.alter_column("priority", existing_type=sa.Integer(), nullable=False)

    if is_sqlite:
        with op.batch_alter_table("hosts") as batch_op:
            batch_op.alter_column('inbound_tag',
                   existing_type=sa.VARCHAR(length=256),
                   nullable=True)
            batch_op.create_foreign_key("hosts_ibfk_1", 'inbounds', ['inbound_tag'], ['tag'], onupdate='CASCADE', ondelete='SET NULL')

    else:
        op.alter_column('hosts', 'inbound_tag',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_bin', length=256),
               nullable=True)
        op.drop_constraint('hosts_ibfk_1', 'hosts', type_='foreignkey')

        op.create_foreign_key("hosts_ibfk_1", 'hosts', 'inbounds', ['inbound_tag'], ['tag'], onupdate='CASCADE', ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    if is_sqlite:
        with op.batch_alter_table("hosts") as batch_op:
            batch_op.drop_constraint('hosts_ibfk_1', type_='foreignkey')
            batch_op.alter_column('inbound_tag',
                       existing_type=sa.VARCHAR(length=256),
                       nullable=False)
            batch_op.create_foreign_key(
                'hosts_ibfk_1', 
                'inbounds', 
                ['inbound_tag'], 
                ['tag']
            )

    else:
        op.drop_constraint('hosts_ibfk_1', 'hosts', type_='foreignkey')
        op.create_foreign_key('hosts_ibfk_1', 'hosts', 'inbounds', ['inbound_tag'], ['tag'])
        op.alter_column('hosts', 'inbound_tag',
                   existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_bin', length=256),
                   nullable=False)

    op.drop_column("hosts", "priority")
    # ### end Alembic commands ###
