export const REPO_URL = 'https://github.com/Gozargah/Marzban'
export const ORGANIZATION_URL = 'https://github.com/Gozargah'
export const DONATION_URL = 'https://donate.gozargah.pro'
export const DISCUSSION_GROUP = 'https://t.me/gozargah_marzban'
export const DOCUMENTATION = 'https://gozargah.github.io/marzban/'
