export const REPO_URL = 'https://github.com/PasarGuard/panel.git'
export const ORGANIZATION_URL = 'https://github.com/PasarGuard'
export const DONATION_URL = 'https://donate.gozargah.pro'
export const DISCUSSION_GROUP = 'https://t.me/Pasar_Guard'
export const DOCUMENTATION = 'https://github.com/PasarGuard/docs'
